# Generated by Django 3.2 on 2022-04-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_phto_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phto',
            new_name='Photo',
        ),
    ]
